name: mFISHwarp
channels:
  - defaults
dependencies:
  - pip==22.2.2
  - python=3.8.12
  - pip:
    - cucim==21.12.0
    - cupy==10.0.0
    - dask==2021.11.2
    - dask-image==0.6.0
    - dask-stitch==0.2.1
    - jupyterlab==3.2.1
    - napari==0.4.15
    - numpy==1.20.0
    - protobuf==3.20
    - ray==1.10.0
    - scikit-image==0.19.2
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - vispy==0.9.6
    - zarr==2.10.2
    - simpleitk==2.1.1
